version: '3.1'

services:
  app:
    build: .
    ports:
      - 7000:7000
      - 4000:4000
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  rd:
    image: redis:alpine
    command: ["redis-server"]
    ports:
      - 6000:6379 
  
volumes:
  postgres_data: {}